# Generated by Django 2.2.12 on 2021-01-16 03:33

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('calificacion', '0002_auto_20210116_0328'),
    ]

    operations = [
        migrations.AlterField(
            model_name='materia',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
